version: '3.8'

services:
  service_1:
    build:
      context: ./service_1
    image: jayakrishnaf5/service_1:latest
    container_name: service_1
    expose:
      - "8001"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8001/ping"]
    #   interval: 10s
    #   timeout: 3s
    #   retries: 3

  service_2:
    build:
      context: ./service_2
    image: jayakrishnaf5/service_2:latest
    container_name: service_2
    expose:
      - "8002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  nginx:
    build:
      context: ./nginx
    image: jayakrishnaf5/nginx:latest
    container_name: nginx
    depends_on:
      service_1:
        condition: service_started
      service_2:
        condition: service_healthy
